prerm, postinst: Fixup lintian warnings, use deb-systemd-helper

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -6,8 +6,12 @@ set -e
 mkdir -p /etc/provisioner
 
 # Set up systemd service
-systemctl daemon-reload
-systemctl enable provisioner.service
-systemctl start provisioner.service
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	deb-systemd-helper daemon-reload >/dev/null || true
+	deb-systemd-helper enable 'provisioner.service' >/dev/null || true
+	if [ -d /run/systemd/system ]; then
+		deb-systemd-invoke start 'provisioner.service' >/dev/null || true
+	fi
+fi
 
 #DEBHELPER#
